"""Privacy Router agents package.

Barrel pattern: import from ``agents`` or ``agents.<subpkg>`` instead
of deep submodule paths.

Public API (convenience re-exports)
------------------------------------
From agents.extractor: detector contract, four backend adapters, registry,
  and current compatibility types
From agents.masker:    Masker, ContractStore, MaskingContract, encrypt_field, decrypt_field
From agents.router:    PrivacyRouter, PipelineResult, RouteResult, MiddleManAgent, RecordOverride, RoutingStrategy, UserAction, UserDecision
From agents.judge:     Judge, Judgment
From agents.llm:       call_llm, call_llm_structured, load_prompt, render_prompt
"""

from agents.extractor import (
    Critic,
    DetectionResult,
    DetectorParseError,
    DetectorParser,
    DetectorRegistry,
    DetectorRunBase,
    DetectorRunProvenance,
    EntityNormalizer,
    ExtractionRecord,
    ExtractionResult,
    Extractor,
    ExtractorCore,
    LFMDetectorRun,
    LFMExtractor,
    LFMParser,
    LLMDetectorRun,
    LLMExtractionOutput,
    LLMExtractor,
    LLMParser,
    LLMRecord,
    OPFDetectorRun,
    OPFExtractor,
    OPFParser,
    ParsedEntity,
    PresidioDetectorRun,
    PresidioExtractor,
    PresidioParser,
    PrivacyAnalysisUnavailable,
    PrivacyEntity,
    PrivacyExtractor,
    RecognizerDescriptor,
    Requiredness,
    Sensitivity,
    SpanReconciliationError,
    extract,
    redact_extraction_records,
)
from agents.judge import Judge, Judgment
from agents.llm import call_llm, call_llm_structured, load_prompt, render_prompt
from agents.masker import (
    ContractStore,
    HydrationError,
    Masker,
    MaskingContract,
    cache_fingerprint,
    decrypt_field,
    encrypt_field,
)
from agents.router import (
    MiddleManAgent,
    PipelineResult,
    PlaceholderRepairDecision,
    PlaceholderRepairer,
    PrivacyRouteFailure,
    PrivacyRouter,
    RecordOverride,
    RouteResult,
    RoutingStrategy,
    UserAction,
    UserDecision,
    execute_fixed_route,
    execute_fixed_stream,
    get_cache,
    log_privacy_failure,
    placeholder_repair_enabled,
    privacy_failure,
    public_error_fields,
)

__all__ = [
    # extractor
    "Critic",
    "ExtractorCore",
    "PrivacyAnalysisUnavailable",
    "Extractor",
    "ExtractionRecord",
    "ExtractionResult",
    "Sensitivity",
    "redact_extraction_records",
    "extract",
    "Requiredness",
    "PrivacyEntity",
    "DetectionResult",
    "DetectorRunBase",
    "DetectorRunProvenance",
    "LLMDetectorRun",
    "PresidioDetectorRun",
    "OPFDetectorRun",
    "LFMDetectorRun",
    "RecognizerDescriptor",
    "ParsedEntity",
    "DetectorParser",
    "DetectorParseError",
    "EntityNormalizer",
    "SpanReconciliationError",
    "LLMRecord",
    "LLMExtractionOutput",
    "LLMExtractor",
    "LLMParser",
    "PresidioExtractor",
    "PresidioParser",
    "OPFExtractor",
    "OPFParser",
    "LFMExtractor",
    "LFMParser",
    "PrivacyExtractor",
    "DetectorRegistry",
    # judge
    "Judge",
    "Judgment",
    # llm
    "call_llm",
    "call_llm_structured",
    "load_prompt",
    "render_prompt",
    # masker
    "ContractStore",
    "HydrationError",
    "Masker",
    "MaskingContract",
    "cache_fingerprint",
    "decrypt_field",
    "encrypt_field",
    # router
    "MiddleManAgent",
    "PipelineResult",
    "PlaceholderRepairDecision",
    "PlaceholderRepairer",
    "placeholder_repair_enabled",
    "PrivacyRouter",
    "RecordOverride",
    "RouteResult",
    "PrivacyRouteFailure",
    "execute_fixed_route",
    "execute_fixed_stream",
    "log_privacy_failure",
    "get_cache",
    "privacy_failure",
    "public_error_fields",
    "RoutingStrategy",
    "UserAction",
    "UserDecision",
]
