"""Schemas for the Extractor package.

All Pydantic models used by the Extractor. Internal models are
prefixed with an underscore and excluded from the barrel.

Notes
-----
Each model uses pydantic.Field with ``description`` and where
relevant, ``examples`` to fully document the contract.
"""

from __future__ import annotations

import secrets
from collections.abc import Iterable
from typing import Annotated, Any, Literal
from uuid import UUID, uuid4

from pydantic import BaseModel, Field, model_validator

# ── Public schemas ───────────────────────────────────────────────────────────


class Sensitivity(BaseModel):
    """Assessment of whether input text contains sensitive information.

    Attributes
    ----------
    is_sensitive : bool
        True if any sensitive information was found.
    rationale : str
        Explanation of the assessment in Korean.

    Examples
    --------
    >>> s = Sensitivity(is_sensitive=True, rationale="주민등록번호(901212-1234567)가 탐지됨")
    >>> s.is_sensitive
    True
    """

    is_sensitive: bool = Field(
        ...,
        description="Whether sensitive information was detected in the text.",
        examples=[True, False],
    )
    rationale: str = Field(
        ...,
        description="Human-readable explanation of the assessment (Korean).",
        examples=[
            "주민등록번호(901212-1234567)가 탐지되어 민감 정보로 분류됩니다.",
            "민감 정보가 발견되지 않았습니다.",
        ],
    )


class ExtractionRecord(BaseModel):
    """A single detected sensitive span.

    Attributes
    ----------
    category : str
        SCREAMING_SNAKE_CASE tag generated by the SLM.
    span : str
        Exact substring that was detected in the original text.
    confidence : float
        Detection confidence, clipped to [0.0, 1.0].
    start : int
        Character offset where the span begins (0-indexed).
    end : int
        Character offset where the span ends (exclusive, 0-indexed).

    Examples
    --------
    >>> r = ExtractionRecord(category="PERSONAL_IDENTIFIER_NUMBER", span="901212-1234567", confidence=0.98, start=7, end=21)
    >>> r.category
    'PERSONAL_IDENTIFIER_NUMBER'
    """

    category: str = Field(
        ...,
        description="Reusable, value-independent SCREAMING_SNAKE_CASE semantic type.",
        examples=["PERSONAL_IDENTIFIER_NUMBER", "UNPUBLISHED_RESEARCH_CONCEPT"],
    )
    span: str = Field(
        ...,
        description="Exact substring matched in the original text.",
        examples=["901212-1234567", "TSMC 3nm 공정 채택"],
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Detection confidence score.",
        examples=[0.98, 0.85],
    )
    start: int = Field(
        ...,
        ge=0,
        description="Start character index in the original text (0-indexed).",
        examples=[7],
    )
    end: int = Field(
        ...,
        ge=0,
        description="End character index in the original text (exclusive, 0-indexed).",
        examples=[21],
    )
    detection_type: str = Field(
        default="contextual",
        description="How this was detected: 'pattern' for fixed formats (RRN, phone), 'contextual' for context-dependent sensitivity.",
        examples=["pattern", "contextual"],
    )
    reasoning: str = Field(
        default="",
        description="One sentence explaining WHY this span is sensitive.",
        examples=["주민등록번호는 개인 식별 정보이므로", "미공개 연구 방법론이므로 경쟁사에게 이점이 됨"],
    )
    is_essential: bool = Field(
        default=False,
        description="True if masking this record would break the query's meaning.",
        examples=[False, True],
    )


class ExtractionResult(BaseModel):
    """Full result of the extraction phase.

    Attributes
    ----------
    sensitivity : Sensitivity
        Whether sensitive information was found and why.
    records : list of ExtractionRecord
        Validated extraction records (empty if nothing was found).

    Examples
    --------
    >>> s = Sensitivity(is_sensitive=True, rationale="탐지됨")
    >>> r = ExtractionResult(sensitivity=s)
    >>> r.records
    []
    """

    sensitivity: Sensitivity = Field(
        ...,
        description="Sensitivity assessment including rationale.",
        examples=[Sensitivity(is_sensitive=True, rationale="주민등록번호 탐지")],
    )
    records: list[ExtractionRecord] = Field(
        default_factory=list,
        description="Validated extraction records.",
        examples=[
            [
                ExtractionRecord(
                    category="RESIDENT_REGISTRATION_NUMBER", span="901212-1234567", confidence=0.98, start=7, end=21
                )
            ]
        ],
    )

    @model_validator(mode="after")
    def records_imply_sensitivity(self) -> ExtractionResult:
        """Treat validated sensitive spans as authoritative evidence."""
        if self.records and not self.sensitivity.is_sensitive:
            self.sensitivity = self.sensitivity.model_copy(update={"is_sensitive": True})
        return self


def redact_extraction_records(
    records: Iterable[ExtractionRecord],
) -> list[dict[str, str | float | bool | int]]:
    """Build public metadata without exposing raw spans or model reasoning."""
    return [
        {
            "index": index,
            "category": record.category,
            "span": "<redacted>",
            "confidence": record.confidence,
            "is_essential": record.is_essential,
        }
        for index, record in enumerate(records)
    ]


# ── Internal schemas (SLM output contracts) ──────────────────────────────────
# The following are the Pydantic shapes the SLM is asked to produce.
# They are NOT part of the public API.


class _ExtractedItem(BaseModel):
    """Shape the SLM produces for a single span.

    Offsets are computed in post-processing via ``text.find(span)``
    — the SLM is NOT asked to produce character offsets.

    Examples
    --------
    >>> item = _ExtractedItem(category="RESIDENT_REGISTRATION_NUMBER", span="901212-1234567", confidence=0.98)
    """

    category: str = Field(
        ...,
        description="SCREAMING_SNAKE_CASE tag from the closed category list.",
        examples=["RESIDENT_REGISTRATION_NUMBER", "FABRICATION_PROCESS_DECISION"],
    )
    span: str = Field(
        ...,
        description="Exact substring from the input text.",
        examples=["901212-1234567"],
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Detection confidence.",
        examples=[0.98],
    )
    detection_type: str = Field(
        default="contextual",
        description="How this was detected: 'pattern' for fixed formats (RRN, phone), 'contextual' for context-dependent sensitivity.",
        examples=["pattern", "contextual"],
    )
    reasoning: str = Field(
        default="",
        description="One sentence explaining WHY this span is sensitive.",
        examples=["주민등록번호는 개인 식별 정보이므로", "미공개 연구 방법론이므로 경쟁사에게 이점이 됨"],
    )
    is_essential: bool = Field(
        default=False,
        description="True if masking this record would break the query's meaning.",
        examples=[False, True],
    )


class _ExtractedOutput(BaseModel):
    """Shape the SLM produces for the complete extraction call.

    Examples
    --------
    >>> s = Sensitivity(is_sensitive=True, rationale="탐지됨")
    >>> o = _ExtractedOutput(sensitivity=s)
    >>> o.records
    []
    """

    sensitivity: Sensitivity = Field(
        ...,
        description="Sensitivity assessment from the SLM.",
        examples=[Sensitivity(is_sensitive=True, rationale="주민등록번호 탐지")],
    )
    records: list[_ExtractedItem] = Field(
        default_factory=list,
        description="Raw extracted items from the SLM.",
        examples=[[_ExtractedItem(category="RESIDENT_REGISTRATION_NUMBER", span="901212-1234567", confidence=0.98)]],
    )


class _CriticItem(BaseModel):
    """A single missed record from the critic pass."""

    category: str = Field(..., description="SCREAMING_SNAKE_CASE category.")
    span: str = Field(..., description="Exact substring the first pass missed.")
    confidence: float = Field(default=0.9, ge=0.0, le=1.0)
    detection_type: str = Field(default="contextual")
    reasoning: str = Field(default="", description="Why this was missed and why it's sensitive.")
    is_essential: bool = Field(
        default=False,
        description="True if masking this record would break the query's meaning.",
    )


class CriticOutput(BaseModel):
    """Second-pass critic output — finds what the Extractor missed."""

    found_missed: bool = Field(..., description="True if any sensitive spans were missed.")
    missed_records: list[_CriticItem] = Field(default_factory=list)


class Requiredness(BaseModel):
    """Whether the entity is required to answer or process the query."""

    value: bool | None = Field(
        default=None,
        description="Whether this entity is required for the user's query response or processing.",
    )
    reason: str | None = Field(
        default=None,
        description="Why the entity is or is not required.",
    )

    @model_validator(mode="after")
    def require_reason(self) -> Requiredness:
        if not self.reason or not self.reason.strip():
            raise ValueError("is_required.reason is required for every value state")
        return self


class PrivacyEntity(BaseModel):
    """One normalized privacy-relevant text entity."""

    id: UUID = Field(default_factory=uuid4, description="Internal identity of this entity record.")
    kind: Literal["contextual", "structural"] = Field(
        ...,
        description="Why the value is privacy-relevant.",
    )
    tag: str = Field(..., min_length=1, description="Canonical privacy tag, such as EMAIL or API_KEY.")
    uid: str = Field(
        default_factory=lambda: secrets.token_hex(16),
        min_length=32,
        max_length=32,
        pattern=r"^[0-9a-f]{32}$",
        description="Occurrence-specific opaque token.",
    )
    span: str = Field(..., min_length=1, description="Exact sensitive substring from the input.")
    offsets: tuple[int, int] = Field(
        ...,
        description="Zero-based, end-exclusive Unicode code-point offsets as (start, end).",
    )
    reason: str | None = Field(default=None, description="Why the detector classified the span as sensitive.")
    confidence: float | None = Field(default=None, ge=0.0, le=1.0)
    native_label: str | None = Field(default=None, description="Original backend label before normalization.")
    native_metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Backend-specific metadata preserved for audit and comparison.",
    )
    detection_method: Literal["regex", "ner", "token_classifier", "llm", "hybrid"] = Field(
        ...,
        description="Mechanism that produced the detection.",
    )
    run_id: UUID = Field(..., description="Detector run that produced this entity.")
    is_required: Requiredness = Field(
        default_factory=lambda: Requiredness(value=None, reason="not assessed"),
        description="Whether this entity is required for the query's response or processing.",
    )

    @model_validator(mode="after")
    def validate_offsets(self) -> PrivacyEntity:
        start, end = self.offsets
        if start < 0 or end <= start:
            raise ValueError("offsets must satisfy 0 <= start < end")
        return self

    @property
    def identifier(self) -> str:
        """Return the computed tag#uid marker without persisting it."""
        return f"{self.tag}#{self.uid}"



class DetectorRunBase(BaseModel):
    """Common provenance for one detector execution."""

    run_id: UUID = Field(default_factory=uuid4)
    detector_type: str
    detector_id: str = Field(
        ...,
        pattern=r"^[a-z0-9]+(?:-[a-z0-9]+)*-v[0-9]+(?:-[0-9]+)*$",
    )
    status: Literal["complete", "partial", "failed"] = "complete"
    external_opt_in: bool = False
    adapter_version: str = Field(
        ...,
        pattern=r"^[a-z0-9]+(?:-[a-z0-9]+)*-v[0-9]+(?:-[0-9]+)*$",
    )
    error_code: str | None = None


class RecognizerDescriptor(BaseModel):
    """Configured Presidio recognizer identity."""

    name: str
    identifier: str | None = None
    version: str | None = None


class LLMDetectorRun(DetectorRunBase):
    """Provenance for the LiteLLM-backed LLM extractor."""

    detector_type: Literal["llm"] = "llm"
    model_id: str
    model_revision: str | None = None
    prompt_version: str | None = None


class PresidioDetectorRun(DetectorRunBase):
    """Provenance for one Presidio analyzer execution."""

    detector_type: Literal["presidio"] = "presidio"
    configured_recognizers: list[RecognizerDescriptor] = Field(default_factory=list)
    package_version: str | None = None


class OPFDetectorRun(DetectorRunBase):
    """Provenance for one OpenAI Privacy Filter execution."""

    detector_type: Literal["opf"] = "opf"
    model_id: str
    model_revision: str | None = None
    output_mode: str = "typed"
    decode_mode: str | None = None


class LFMDetectorRun(DetectorRunBase):
    """Provenance for one LFM2.5 detector execution."""

    detector_type: Literal["lfm"] = "lfm"
    model_id: str
    model_revision: str | None = None
    decoder_revision: str | None = None
    device: str | None = None


DetectorRunProvenance = Annotated[
    LLMDetectorRun | PresidioDetectorRun | OPFDetectorRun | LFMDetectorRun,
    Field(discriminator="detector_type"),
]


class DetectionResult(BaseModel):
    """Normalized detector output with auditable execution provenance."""

    status: Literal["complete", "partial", "failed"] = "complete"
    entities: list[PrivacyEntity] = Field(default_factory=list)
    detector_runs: list[DetectorRunProvenance] = Field(default_factory=list)
    diagnostics: dict[str, list[str]] = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_entity_references(self) -> DetectionResult:
        ids = [entity.id for entity in self.entities]
        uids = [entity.uid for entity in self.entities]
        run_ids = {run.run_id for run in self.detector_runs}
        if len(ids) != len(set(ids)):
            raise ValueError("entity ids must be unique within a detection result")
        if len(uids) != len(set(uids)):
            raise ValueError("entity uids must be unique within a detection result")
        missing_run_ids = {entity.run_id for entity in self.entities} - run_ids
        if missing_run_ids:
            raise ValueError(f"entities reference unrecorded run_id values: {sorted(missing_run_ids)}")
        return self

    def token_map(self) -> dict[str, str]:
        """Derive identifier-to-value mapping without storing a duplicate binding list."""
        return {entity.identifier: entity.span for entity in self.entities}

